### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by xiaonguyen** [Braziliana/T_TApe#3]
worked earlier this day, but stopped working after the newest apex-update with the error:"T_T Ape 1.1.7
Size: 1920, 1080
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
[1]    9120 IOT instruction (core dumped)  ./T_TApe"
- occurs as soon as the round starts

**Comment by Snomn123** [comment]
offsets wrong

**Comment by xiaonguyen** [comment]
here are the new offsets; https://pastebin.com/tTeB4K1t
- just replace /home/username/Downloads/glfw/build/T_TApe/Game/Offsets.hpp

**Comment by Gasferr** [comment]
> here are the new offsets; https://pastebin.com/tTeB4K1t
> 
> * just replace /home/username/Downloads/glfw/build/T_TApe/Game/Offsets.hpp
change ulong weaponPunch = 0x24b0;  RCS working

**Comment by xiaonguyen** [comment]
> > here are the new offsets; https://pastebin.com/tTeB4K1t
> > 
> > * just replace /home/username/Downloads/glfw/build/T_TApe/Game/Offsets.hpp
> change ulong weaponPunch = 0x24b0;  RCS working

Oh thanks

**Comment by Gasferr** [comment]
> > > here are the new offsets; https://pastebin.com/tTeB4K1t
> > > 
> > > * just replace /home/username/Downloads/glfw/build/T_TApe/Game/Offsets.hpp
> > >   change ulong weaponPunch = 0x24b0;  RCS working
> 
> Oh thanks

aimbot not working

**Comment by xiaonguyen** [comment]
Works for me, though need to use BuildAndRun instead of the default method. Last used it ~3h ago, if there wasn't an update during that period, try the above-mentioned method or double-check/redump offsets. 
(+ Don't test it on the firing range, doesn't work there, even if it's PvP)

**Comment by Gasferr** [comment]
> Works for me, though need to use BuildAndRun instead of the default method. Last used it ~3h ago, if there wasn't an update during that period, try the above-mentioned method or double-check/redump offsets. (+ Don't test it on the firing range, doesn't work there, even if it's PvP)
working using buildand run

**Comment by Czy2019** [comment]
> Works for me, though need to use BuildAndRun instead of the default method. Last used it ~3h ago, if there wasn't an update during that period, try the above-mentioned method or double-check/redump offsets. (+ Don't test it on the firing range, doesn't work there, even if it's PvP)

T_T Ape 1.1.7
Size: 1920, 1080
terminate called after throwing an instance of 'std::system_error'
what(): Invalid argument
Aborted

I try to use
"here are the new offsets; https://pastebin.com/tTeB4K1t just replace /home/username/Downloads/glfw/build/T_TApe/Game/Offsets.hpp"
and
"Works for me, though need to use BuildAndRun instead of the default method. Last used it ~3h ago, if there wasn't an update during that period, try the above-mentioned method or double-check/redump offsets.
(+ Don't test it on the firing range, doesn't work there, even if it's PvP)"
Still the same
